# Assignment 1: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [2]:
#3.2: create a random 10x10 array named A
A=np.random.rand(10,10)
A

array([[0.48761713, 0.38616823, 0.44550015, 0.33923791, 0.82974873,
        0.9125555 , 0.89043875, 0.12037823, 0.38836188, 0.69787621],
       [0.0717862 , 0.47353153, 0.06141906, 0.99962624, 0.51256535,
        0.70213902, 0.89012419, 0.32604673, 0.19431862, 0.38087011],
       [0.16060765, 0.86926417, 0.40125352, 0.90690487, 0.90279175,
        0.46687053, 0.16557015, 0.48483075, 0.11945841, 0.32668951],
       [0.26853982, 0.23268913, 0.36272627, 0.30370665, 0.20700737,
        0.38375694, 0.84346744, 0.90534363, 0.29595238, 0.81141366],
       [0.07690271, 0.09912429, 0.90118389, 0.14422459, 0.97348584,
        0.43892545, 0.1818034 , 0.17482001, 0.54503814, 0.51915591],
       [0.41451178, 0.15434862, 0.85317432, 0.83942795, 0.2803666 ,
        0.52465087, 0.59784699, 0.12535169, 0.58734737, 0.54415448],
       [0.47302281, 0.18290066, 0.6352522 , 0.98322476, 0.21515496,
        0.46824955, 0.5928772 , 0.40785929, 0.59349786, 0.44168556],
       [0.18919849, 0.88190168, 0.5488770

In [3]:
#3.3: return only the odd rows of A
A[1::2]

array([[0.0717862 , 0.47353153, 0.06141906, 0.99962624, 0.51256535,
        0.70213902, 0.89012419, 0.32604673, 0.19431862, 0.38087011],
       [0.26853982, 0.23268913, 0.36272627, 0.30370665, 0.20700737,
        0.38375694, 0.84346744, 0.90534363, 0.29595238, 0.81141366],
       [0.41451178, 0.15434862, 0.85317432, 0.83942795, 0.2803666 ,
        0.52465087, 0.59784699, 0.12535169, 0.58734737, 0.54415448],
       [0.18919849, 0.88190168, 0.54887706, 0.31086628, 0.6881984 ,
        0.52061366, 0.98520418, 0.55966699, 0.41959782, 0.17766126],
       [0.77416905, 0.18799051, 0.35886136, 0.17451428, 0.27621472,
        0.87785163, 0.99316358, 0.2449821 , 0.02451791, 0.70204483]])

In [4]:
#3.4: perform a matrix multiplication of A with it's transposed
# print(A.T)
A_transposed=A.dot(A.T)
A_transposed

array([[3.66691783, 2.82349772, 2.5557229 , 2.54863146, 2.49138212,
        2.79328105, 2.63941677, 3.06049894, 2.74183101, 3.1127499 ],
       [2.82349772, 3.06958202, 2.59800644, 2.24341743, 1.58161051,
        2.40085787, 2.52576489, 2.7025747 , 2.33236302, 2.33510276],
       [2.5557229 , 2.59800644, 3.18136756, 1.91145124, 2.02426541,
        2.21011378, 2.30549845, 2.70614499, 2.16768349, 1.76471319],
       [2.54863146, 2.24341743, 1.91145124, 2.81725174, 1.67853402,
        2.20412518, 2.32621392, 2.49778813, 2.29789162, 2.46526732],
       [2.49138212, 1.58161051, 2.02426541, 1.67853402, 2.61920697,
        2.17355775, 1.91563953, 2.13778863, 2.08376897, 1.68216419],
       [2.79328105, 2.40085787, 2.21011378, 2.20412518, 2.17355775,
        2.99626829, 2.89213129, 2.41215263, 2.71860158, 2.36147888],
       [2.63941677, 2.52576489, 2.30549845, 2.32621392, 1.91563953,
        2.89213129, 2.95820723, 2.4368401 , 2.70185467, 2.2839967 ],
       [3.06049894, 2.7025747 , 2.7061449

In [5]:
#3.5: compute the matrix inverse of A
A_inverse=np.linalg.inv(A)
A_inverse

array([[ 1.2498637 , -1.43290083,  0.33347236, -0.38806432, -0.5840306 ,
        -1.42247309,  2.41028368, -0.08844374, -0.48154744,  0.23924276],
       [ 1.28971897, -1.11964123,  0.96076702,  0.44951107, -1.73025435,
         1.8441965 , -1.78967753,  0.47295492,  0.2768104 , -0.99792405],
       [-2.31180951,  0.25566786,  0.06467034, -0.32410788,  0.9697771 ,
         1.48617408, -1.23529843,  0.50528418,  0.03205042,  1.25945607],
       [-0.36090515,  0.59637177,  0.21772658, -0.16534557, -0.01601544,
         0.20375803,  0.48842946, -0.38166797, -0.24553733, -0.04284194],
       [ 0.59926061,  0.18873362, -0.04683913, -0.28716512,  0.89968243,
        -1.57495737,  1.40525778, -0.12019963, -0.66936395, -0.12755767],
       [-1.63137667,  1.04403826, -0.14386605, -0.91476418,  0.9116087 ,
        -0.90438022, -0.47106873, -0.04127168,  1.292025  ,  1.51894168],
       [-0.06250256,  0.62358903, -0.79295182,  0.10851306,  0.03162123,
         0.39135527, -0.07266889,  0.57992681

In [6]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

In [7]:
A

array([[0.48761713, 0.38616823, 0.44550015, 0.33923791, 0.82974873,
        0.9125555 , 0.89043875, 0.12037823, 0.38836188, 0.69787621],
       [0.0717862 , 0.47353153, 0.06141906, 0.99962624, 0.51256535,
        0.70213902, 0.89012419, 0.32604673, 0.19431862, 0.38087011],
       [0.16060765, 0.86926417, 0.40125352, 0.90690487, 0.90279175,
        0.46687053, 0.16557015, 0.48483075, 0.11945841, 0.32668951],
       [0.26853982, 0.23268913, 0.36272627, 0.30370665, 0.20700737,
        0.38375694, 0.84346744, 0.90534363, 0.29595238, 0.81141366],
       [0.07690271, 0.09912429, 0.90118389, 0.14422459, 0.97348584,
        0.43892545, 0.1818034 , 0.17482001, 0.54503814, 0.51915591],
       [0.41451178, 0.15434862, 0.85317432, 0.83942795, 0.2803666 ,
        0.52465087, 0.59784699, 0.12535169, 0.58734737, 0.54415448],
       [0.47302281, 0.18290066, 0.6352522 , 0.98322476, 0.21515496,
        0.46824955, 0.5928772 , 0.40785929, 0.59349786, 0.44168556],
       [0.18919849, 0.88190168, 0.5488770

In [8]:
# create mask 
mask = (A > 0.5)
mask

array([[False, False, False, False,  True,  True,  True, False, False,
         True],
       [False, False, False,  True,  True,  True,  True, False, False,
        False],
       [False,  True, False,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True, False,
         True],
       [False, False,  True, False,  True, False, False, False,  True,
         True],
       [False, False,  True,  True, False,  True,  True, False,  True,
         True],
       [False, False,  True,  True, False, False,  True, False,  True,
        False],
       [False,  True,  True, False,  True,  True,  True,  True, False,
        False],
       [False, False,  True,  True, False,  True, False, False,  True,
         True],
       [ True, False, False, False, False,  True,  True, False, False,
         True]])

In [9]:
# generate indices
indices =np.where(mask)
indices

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5,
        5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9],
       dtype=int64),
 array([4, 5, 6, 9, 3, 4, 5, 6, 1, 3, 4, 6, 7, 9, 2, 4, 8, 9, 2, 3, 5, 6,
        8, 9, 2, 3, 6, 8, 1, 2, 4, 5, 6, 7, 2, 3, 5, 8, 9, 0, 5, 6, 9],
       dtype=int64))

In [11]:
# Divide at indices the values by 2
A[indices]=A[indices]/2
A

array([[0.48761713, 0.38616823, 0.44550015, 0.33923791, 0.41487436,
        0.45627775, 0.44521937, 0.12037823, 0.38836188, 0.34893811],
       [0.0717862 , 0.47353153, 0.06141906, 0.49981312, 0.25628267,
        0.35106951, 0.44506209, 0.32604673, 0.19431862, 0.38087011],
       [0.16060765, 0.43463209, 0.40125352, 0.45345244, 0.45139587,
        0.46687053, 0.16557015, 0.48483075, 0.11945841, 0.32668951],
       [0.26853982, 0.23268913, 0.36272627, 0.30370665, 0.20700737,
        0.38375694, 0.42173372, 0.45267182, 0.29595238, 0.40570683],
       [0.07690271, 0.09912429, 0.45059194, 0.14422459, 0.48674292,
        0.43892545, 0.1818034 , 0.17482001, 0.27251907, 0.25957796],
       [0.41451178, 0.15434862, 0.42658716, 0.41971398, 0.2803666 ,
        0.26232544, 0.2989235 , 0.12535169, 0.29367369, 0.27207724],
       [0.47302281, 0.18290066, 0.3176261 , 0.49161238, 0.21515496,
        0.46824955, 0.2964386 , 0.40785929, 0.29674893, 0.44168556],
       [0.18919849, 0.44095084, 0.2744385

In [13]:
# check if in mask all values are false
mask = (A > 0.5)
mask

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])